app = "coder-neon" # Replace <coder-app-name> with the name of your app
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"  # See a list of regions here: https://fly.io/docs/reference/regions/

[experimental]
    auto_rollback = true
    private_network = true  # Allows Coder to connect to the database

[build]
     image = "ghcr.io/coder/coder:v2.22.1"

[deploy]
  strategy = "immediate"

[env]
    CODER_ACCESS_URL = "https://coder-neon.fly.dev" # Replace <app-name> with the name of your app
    CODER_HTTP_ADDRESS = "0.0.0.0:3000"
    #CODER_VERBOSE = "true" # Uncomment this if you want to see more logs
    CODER_TELEMETRY_INSTALL_SOURCE = "fly.io"
    CODER_PROXY_TRUSTED_HEADERS = "Fly-Client-IP"
    CODER_DERP_CONFIG_URL = "https://controlplane.tailscale.com/derpmap/default"
    CODER_PROVISIONER_DAEMONS = 2
    CODER_SESSION_DURATION = "168h" # 7 days

[[services]]
    protocol = "tcp"
    internal_port = 3000
    processes = ["app"]

    [[services.ports]]
        port = 80
        handlers = ["http"]
        force_https = true

    [[services.ports]]
        port = 443
        handlers = ["tls", "http"]

    [services.concurrency]
        type = "connections"
        hard_limit = 25

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[checks]
  [checks.coder_http_check]
    grace_period = "5s"
    interval = 5000
    timeout = 2000
    port = 3000
    type = "http"
    method = "get"
    path = "/healthz"
