kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"  # See a list of regions here: https://fly.io/docs/reference/regions/

[experimental]
    auto_rollback = true

[build]
    image = "ghcr.io/coder/coder:v2.23.1"

[deploy]
    strategy = "rolling"

[env]
    CODER_ACCESS_URL = "https://coderd.fly.dev" # Replace <app-name> with the name of your app
    CODER_HTTP_ADDRESS = "0.0.0.0:3000"
    #CODER_VERBOSE = "true" # Uncomment this if you want to see more logs
    CODER_TELEMETRY_INSTALL_SOURCE = "fly.io"
    CODER_PROXY_TRUSTED_HEADERS = "Fly-Client-IP"
    CODER_DERP_CONFIG_URL = "https://controlplane.tailscale.com/derpmap/default"
    CODER_PROVISIONER_DAEMONS = 1
    CODER_SESSION_DURATION = "168h" # 7 days

[[services]]
    protocol = "tcp"
    internal_port = 3000
    processes = ["app"]
    auto_stop_machines = "suspend"
    auto_start_machines = true
    min_machines_running = 0

    [[services.ports]]
        port = 80
        handlers = ["http"]
        force_https = true

    [[services.ports]]
        port = 443
        handlers = ["tls", "http"]

    [services.concurrency]
        type = "connections"
        hard_limit = 25

[[vm]]
    size = "shared-cpu-1x"
    memory = "512mb"

#[checks]
#    [checks.coder_http_check]
#        grace_period = "5s"
#        interval = 10000
#        timeout = 3000
#        port = 3000
#        type = "http"
#        method = "get"
#        path = "/healthz"
